### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Sebazztian** [agelber/more-than-today#1]
It does not work anymore.
It shows "loading not possible".
iOS 9.2.1, iPhone 6S Plus

**Comment by Sebazztian** [comment]
I tried rebooting and disabling calendars.

**Comment by Sebazztian** [comment]
Sorry, could solve this by reinstalling the app.

**Comment by agelber** [comment]
Thanks for filing this, I would still be happy to hear more info though, to see if I can prevent this in the the future.
